FIND_PATH(MsgPack_INCLUDE_DIR msgpack.hpp)
FIND_LIBRARY(MsgPack_LIBRARY NAMES msgpack)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	MsgPack REQUIRED_VARS
	MsgPack_INCLUDE_DIR
	MsgPack_LIBRARY)
